(import (chezscheme)
        (bus))

(define (string-contains? str substr)
  (let ([str-length (string-length str)]
        [sub-length (string-length substr)])
    (cond
     [(< str-length sub-length) #f]
     [(string=? (substring str 0 sub-length) substr) #t]
     [else (string-contains? (substring str 1 str-length) substr)])))

(define (count predicate list)
  (let loop ([list list] [acc 0])
    (if (null? list)
        acc
        (loop (cdr list) (if (predicate (car list))
                             (+ acc 1)
                             acc)))))

(define (say formatting . arguments)
  (apply format #t (string-append "; " formatting "~%")
         arguments))

(define (run-tests)
  (let ([results '()])
    (define (test name test-body)
      (let ([result (test-body)])
        (set! results (cons (cons name result) results))
        (say "~90,1,1,'.@<~A ~> ~A ~S" name (if result "OK" "FAIL") result)
        result))

    (test "make-event-bus returns a procedure" (lambda () (procedure? (make-event-bus))))

    (test "'attach and 'propagate with single receiver" (lambda ()
                                                          (let* ((bus (make-event-bus))
                                                                 (output (open-output-string))
                                                                 (receiver (lambda (x)
                                                                             (display (string-append "Got: " x) output))))
                                                            (bus 'attach 'test-event receiver)
                                                            (bus 'propagate 'test-event "hello")
                                                            (bus 'propagate 'test-event "world")
                                                            (let ((result (get-output-string output)))
                                                              (and (string-contains? result "Got: hello")
                                                                   (string-contains? result "Got: world"))))))

    (test "multiple receivers for same event" (lambda ()
                                                (let* ((bus (make-event-bus))
                                                       (output1 (open-output-string))
                                                       (output2 (open-output-string))
                                                       (receiver1 (lambda (x y)
                                                                    (display (string-append "R1:" x y) output1)))
                                                       (receiver2 (lambda (x y)
                                                                    (display (string-append "R2:" x y) output2))))
                                                  (bus 'attach 'multi receiver1)
                                                  (bus 'attach 'multi receiver2)
                                                  (bus 'propagate 'multi "a" "b")
                                                  (let ((r1 (get-output-string output1))
                                                        (r2 (get-output-string output2)))
                                                    (and (string=? r1 "R1:ab")
                                                         (string=? r2 "R2:ab"))))))

    (test "'detach removes receiver" (lambda ()
                                       (let* ((bus (make-event-bus))
                                              (output (open-output-string))
                                              (receiver (lambda ()
                                                          (display "called" output))))
                                         (bus 'attach 'detach-test receiver)
                                         (bus 'propagate 'detach-test)
                                         (bus 'detach 'detach-test receiver)
                                         (bus 'propagate 'detach-test)
                                         (let ((result (get-output-string output)))
                                           (string=? result "called")))))

    (test "'receivers returns vector of all receivers" (lambda ()
                                                         (let* ((bus (make-event-bus))
                                                                (r1 (lambda () 1))
                                                                (r2 (lambda () 2))
                                                                (r3 (lambda () 3)))
                                                           (bus 'attach 'event-a r1)
                                                           (bus 'attach 'event-a r2)
                                                           (bus 'attach 'event-b r3)
                                                           (let ((vec (bus 'receivers)))
                                                             (and (vector? vec)
                                                                  (= (vector-length vec) 2))))))

    (test "'receivers with event returns list for that event" (lambda ()
                                                                (let* ((bus (make-event-bus))
                                                                       (r1 (lambda () 1))
                                                                       (r2 (lambda () 2))
                                                                       (r3 (lambda () 3)))
                                                                  (bus 'attach 'event-a r1)
                                                                  (bus 'attach 'event-a r2)
                                                                  (bus 'attach 'event-b r3)
                                                                  (let ((lst (bus 'receivers 'event-a)))
                                                                    (and (list? lst)
                                                                         (= (length lst) 2)
                                                                         (memq r1 lst)
                                                                         (memq r2 lst))))))

    (test "'reset clears all receivers" (lambda ()
                                          (let* ((bus (make-event-bus))
                                                 (output (open-output-string))
                                                 (receiver (lambda () (display "x" output))))
                                            (bus 'attach 'event1 receiver)
                                            (bus 'attach 'event2 receiver)
                                            (bus 'reset)
                                            (bus 'propagate 'event1)
                                            (bus 'propagate 'event2)
                                            (let ((result (get-output-string output)))
                                              (string=? result "")))))

    (test "'propagate with multiple arguments" (lambda ()
                                                 (let* ((bus (make-event-bus))
                                                        (result (box '()))
                                                        (receiver (lambda args
                                                                    (set-box! result args))))
                                                   (bus 'attach 'multi-args receiver)
                                                   (bus 'propagate 'multi-args 'a 'b 'c 'd)
                                                   (equal? (unbox result) '(a b c d)))))

    (test "'propagate with no receivers does nothing" (lambda ()
                                                        (let ((bus (make-event-bus)))
                                                          (bus 'propagate 'non-existent 'arg1 'arg2)
                                                          #t)))

    (test "'detach non-existent receiver does nothing" (lambda ()
                                                         (let* ((bus (make-event-bus))
                                                                (r1 (lambda () 1))
                                                                (r2 (lambda () 2)))
                                                           (bus 'attach 'event r1)
                                                           (bus 'detach 'event r2)
                                                           (let ((lst (bus 'receivers 'event)))
                                                             (= (length lst) 1)))))

    (test "'receivers for non-existent event returns empty list" (lambda ()
                                                                   (let ((bus (make-event-bus)))
                                                                     (null? (bus 'receivers 'no-such-event)))))

    (test "receivers maintain attachment order (LIFO)" (lambda ()
                                                         (let* ((bus (make-event-bus))
                                                                (output (open-output-string))
                                                                (r1 (lambda () (display "1" output)))
                                                                (r2 (lambda () (display "2" output)))
                                                                (r3 (lambda () (display "3" output))))
                                                           (bus 'attach 'order r1)
                                                           (bus 'attach 'order r2)
                                                           (bus 'attach 'order r3)
                                                           (bus 'propagate 'order)
                                                           (let ((result (get-output-string output)))
                                                             (string=? result "321")))))

    (test "receiver attachment can be checked using 'has-attached?" (lambda ()
                                                                      (let* ((bus (make-event-bus))
                                                                             (r1 (lambda () 1))
                                                                             (r2 (lambda () 2)))
                                                                        (bus 'attach 'event r1)
                                                                        (and (bus 'has-attached? 'event r1)
                                                                             (not (bus 'has-attached? 'event r2))))))

    (let ([passed (count cdr results)]
          [total (length results)])
      (say "Passed ~D test~:P out of ~D." passed total)
      (= passed total))))

(exit (if (run-tests) 0 1))
